import "./globals.css";
import { Inter } from "next/font/google";

// Define font family
const inter = Inter({ subsets: ["latin"] });

// Define metadata
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    );
}
